# Generated by Django 5.0.3 on 2024-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_topic_room_host_room_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='product name')),
                ('price', models.IntegerField()),
                ('pdetail', models.CharField(max_length=300, verbose_name='Product detail')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
